package org.hobby.database

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Query

/**
 * Data Access Object autogenerated
 */
@Dao
abstract class BooleanSettingDAO {
    @Query("SELECT * FROM boolean_setting")
    abstract fun getAll(): List<BooleanSetting>

    @Query("SELECT * FROM boolean_setting WHERE path IN (:paths)")
    abstract fun loadAllByPathss(paths: List<String>): List<BooleanSetting>

    @Query("SELECT * FROM boolean_setting WHERE path = :path LIMIT 1")
    abstract fun findByPath(path: String): BooleanSetting

    @Insert
    abstract fun insertAll(vararg users: BooleanSetting)

    @Delete
    abstract fun delete(user: BooleanSetting)

}